---

- name: Create a EC2 Instance
  hosts: localhost
  gather_facts: false
  vars:
    keypair: id_rsa
    instance_type: t2.micro
    image: ami-467ca739
    region: us-east-1
  tasks:
    - name: Launch Instance
      ec2:
         key_name: "{{keypair}}"
         group: default
         instance_type: "{{instance_type}}"
         image: "{{ image }}"
         wait: true
         region: "{{region}}"
#         aws_access_key: "{{AWS_ACCESS_KEY_ID}}"
#         aws_secret_key: "{{AWS_SECRET_ACCESS_KEY}}"
      register: ec2
    - name: Print all ec2 variables
      debug: var=ec2
